---

  #==================================================
  # SSM Automation Document / Runbook:
  # Defines the configuration as well as the
  # the steps to be run by SSM Automation
  #==================================================

description: |
  ### Document Name - AWS-OpenSecurityGroup

  ## What does this document do?
  This document by default opens port 22 (SSH) in a given Security Group to test automated remediation response. 

  The script will authorize and ingress rule then check for the maximum defined duration whether the rule has been revoked.

  Once it detects the rule has been revoked the automation completes. If the rule exists after the maximum duration the rule will be revoked.

  ## Security Risk
  High: By default opens SSH to the world for a given security group the rule is marked with the FIS experiment ID.

  The script will only allow the rule to exist for the maximum time specified in the input parameters.

  ## Input Parameters
  * SecurityGroupId: (Required) Security group id, This security group will targeted to add the demo rule.
  * AutomationAssumeRole: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
  * RuleProtocol: (Optional) ** Default: TCP ** Protocol for ingress rule to be authorized.
  * RulePort: (Optional) ** Default 22 ** Port for ingress rule to the authorized.
  * RuleCIDR: (Optional) ** Default 0.0.0.0/0 ** CIDR for ingress rule to the authorized.
  * TestDurationInMinutes: (Optional) ** Default 1 minute ** Maximum duration the test rule can exist for.

  ## Supports Rollback
  Yes. rule is Revoked.

  ## Cancellation behaviour
  Revoke ingress rule that was added.   

  ## Output Parameters
  This document has no outputs.

  ## Minimum Permissions Required
  * `ec2:RevokeSecurityGroupIngress`
  * `ec2:AuthorizeSecurityGroupIngress`
  * `ec2:DescribeSecurityGroups`

  ## Additional Permissions for logging
  * logs:CreateLogStream
  * logs:CreateLogGroup
  * logs:PutLogEvents
  * logs:DescribeLogGroups
  * logs:DescribeLogStreams

schemaVersion: '0.3'

#==================================================
# Role assumed my the automation document / runbook
#==================================================
assumeRole: '{{AutomationAssumeRole}}'

#==================================================
# SSM automation document parameters
#==================================================

parameters:
  SecurityGroupId:
    type: String
    description: (Required) The security group ID.
    allowedPattern: '^(sg-)([0-9a-f]){1,}$'
  RuleProtocol:
    type: String
    description: (Optional) The Protocol to Authorize.
    default: 'TCP'
  RulePort:
    type: Integer
    description: (Optional) The Port to Authorize.
    allowedPattern: '^([0-9]{1,4}|[1-5][0-9]{4}|6[0-4][0-9]{3}|65[0-4][0-9]{2}|655[0-2][0-9]|6553[0-5])$'
    default: 22
  RuleCIDR:
    type: String
    description: (Optional) The CIDR to Authorize.
    allowedPattern: '^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))?$'
    default: '0.0.0.0/0'
  AutomationAssumeRole:
    type: String
    description: (Optional) The ARN of the role that allows Automation to perform the actions on your behalf.
    default: ''
    allowedPattern: '^arn:aws(-cn|-us-gov)?:iam::\d{12}:role\/[\w+=,.@_\/-]+|^$'
  TestDurationInMinutes:
    type: String
    description: (Optional) Test duration in minutes.
    default: "1"

#==================================================
# Automation steps
#==================================================

mainSteps:

  #==================================================
  # Authorize the ingress rule as per parameters,
  # Then move to the check for remediation step.
  #==================================================

  - name: AuthorizeSecurityIngressRule
    description: Authorize Security Group Ingress.
    action: 'aws:executeAwsApi'
    onFailure: Abort
    nextStep: 'CheckForRemediation'
    outputs:
      - Name: SecurityGroupRuleId
        Selector: $.SecurityGroupRules[0].SecurityGroupRuleId
        Type: String
    inputs:
      Service: ec2
      Api: AuthorizeSecurityGroupIngress
      GroupId: '{{SecurityGroupId}}'
      IpPermissions:
        - IpProtocol: '{{RuleProtocol}}'
          FromPort: '{{RulePort}}'
          ToPort: '{{RulePort}}'
          IpRanges:
            - CidrIp: '{{RuleCIDR}}'
              Description: 'Added by FIS Experiment. ExecutionID: {{automation:EXECUTION_ID}}'                 

  #==================================================
  # Check if the rule has been revoked
  # Runs a script that loops until the rule is revoked
  # or until the time limit is reached, if this happens
  # we move to the Revoke step.
  #==================================================

  - name: CheckForRemediation
    description: Check for remediation for the duration of the experiment or until rule is removed. 
    action: 'aws:executeScript'
    onFailure: 'step:RevokeSecurityIngressRule'
    onCancel: 'step:RevokeSecurityIngressRule'
    isEnd: true
    isCritical: true
    inputs:
      Runtime: python3.7
      Handler: check_for_remediation_handler
      InputPayload:
        Duration: '{{TestDurationInMinutes}}'
        SecurityGroupRuleId: '{{ AuthorizeSecurityIngressRule.SecurityGroupRuleId }}'
      Script: |
        import boto3
        import logging
        from time import sleep

        logger = logging.getLogger()
        logger.setLevel(logging.INFO)

        ec2_resource = boto3.resource("ec2")
        ec2_client = boto3.client("ec2")

        def check_for_remediation_handler(event, context):


            sgr_id = event["SecurityGroupRuleId"]
            max_duration = event["Duration"]
            max_retries = int((int(max_duration) * 60 ) / 10)
            errorMsg = ""

            logger.info(f'event content: {event}')
            logger.info(f'max retries: {max_retries}')
            logger.info(f'max duration: {max_duration}')
            logger.info('Checking for rule remediation')

            # Test every 10 seconds until max duration is reached

            logger.info(f'checking if rule {sgr_id} exists')

            for x in range (0, max_retries):                   
                try:
                    check_rule = ec2_client.describe_security_group_rules(SecurityGroupRuleIds = [sgr_id])
                    if check_rule:                            
                        logger.info(f'rule {sgr_id} still exists, waiting 10s for a max {max_duration}m before checking again')
                        sleep(10)

                except Exception as e:
                    errorMsg = str(e)
                    if "InvalidSecurityGroupRuleId.NotFound" in errorMsg:
                        # This is what we want. The security group rule was removed, before the time expired.
                        logger.info(f'Rule {sgr_id} has been removed, experiment is a success')
                        return {'ExperimentSuccess': f'Security group rule {sgr_id} was remediated' }

                    raise Exception(errorMsg)                  
            
            # Loop completed without success, experiment timer breached so we need to clean up.
            logger.info(f'Rule {sgr_id} still existed at max experiment duration. Rollback will be performed')
            raise Exception(f'Security group rule {sgr_id} still exists after max experiment duration exceeded')

  #==================================================
  # Revoke ingress rule. Step revokes the rule that was
  # created in the AuthorizeSecurityGroupIngressRule step
  #==================================================

  - name: RevokeSecurityIngressRule
    description: Revoke Security Group Ingress.
    action: 'aws:executeAwsApi'
    isEnd: true
    inputs:
      Service: ec2
      Api: RevokeSecurityGroupIngress
      GroupId: '{{SecurityGroupId}}'
      SecurityGroupRuleIds:
        - '{{ AuthorizeSecurityIngressRule.SecurityGroupRuleId }}'           

