service: AutomationRollback

provider:
  name: aws
  runtime: python3.8
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "ec2:*"
      Resource: "*"

functions:
  hello:
    handler: rollback_fault.rollback
    timeout: 300

